### ISSUE TITLE
Boto / Web / Deploy - Password? 

### ISSUE THREAD

**Issue by bgrrtt** [everysquare/craft-ops#5]
Fresh clone, everything seems to be working great after the boto update. 

BUT I can't figure out which password works at this spot (below - I changed the public IP to zeros, but the correct IP is present for me). I assumed it was the passwords generated in private.conf after running "fab setup", but they don't seem to work. I'm sorta new to ssh, but I know enough to question if I'm even supposed to be prompted for a password. Though, I don't know.

THANKS SO MUCH FOR THIS! Craft is already excellent to work with and this ops setup helps streamline the whole process. Also, you opened my eyes to how awesome AWS is. THANKS!

project_folder ❯❯❯ vagrant up
project_folder ❯❯❯ vagrant ssh (automatically dev because of boto, correct?)

vagrant@ubuntu-14 /project — u:1 j:0vboxguest             272665  2 vboxsf
 git:master (22:40:14 10.01)
#113 ❯❯❯ fab staging deploy
[00.0.00.00] Executing task 'deploy'
[00.0.00.00] run: cd $HOME/source && git fetch origin master
[00.0.00.00] Login password for 'staging':
[00.0.00.00] Login password for 'staging':

(I do run into problems when I try to do the ~/ops.conf you suggested though. Something about line 8 in the fabfile not being explicit. Vagrant won't even up or anything. When I switch back to just a private.conf (no ~/ops.conf) everything works fine.)

**Comment by howardroark** [comment]
Yeah. This is probably confusing!  There no longer is Vagrant for the web server.  Mainly because they don't really look at it as a production server tool. The web VM starts right away and intends to stay that way.

I use ssh key forwarding to get my host key onto the vm user. Though the undocumented feature is the `deploy_keys` object that lets you add public keys that you want to have access to the web server.

Any suggestions are welcome!

**Comment by howardroark** [comment]
Would it be helpful if the `fab setup` command auto generated a `dev` key pair for use on the `dev` vm and then added that info to the project config file?

**Comment by bgrrtt** [comment]
Yea, actually. I think I understand what that means. So that would take care of the password prompt I see when ssh-ed into vagrant when running "fab {{ stage }} deploy"? I was just about to ask about ssh forwarding though... do I add something like "deploy_keys ~/.ssh/id_rsa" to salt/dev/files/ssh_config above ForwardAgent OR... Or, is there a post somewhere that you know about that could help? 

I think with your boto commit, you committed to production security. I am happy about that.

**Comment by howardroark** [comment]
I think ssh forwarding is probably only relevant if you have a key that you currently use for bitbucket and command line git on your host machine. Maybe a user that has access to the "team".  In that case you would update your ~/.ssh/config file with...

```
ForwardAgent yes
```

https://developer.github.com/guides/using-ssh-agent-forwarding/

**Comment by bgrrtt** [comment]
So in ~/.ssh/config 

ForwardAgent yes OR

Host bitbucket.org
  ForwardAgent yes

Doesn't seem to work... Provisioned (just in case) between attempts.

Am I supposed to see a password prompt after running the deploy command?

**Comment by howardroark** [comment]
No the password prompt is a default behaviour of the deploy tool `fabric`.  The first option you mention there would cover all cases.  You also need to run `fab web provision` within the vm after that.

**Comment by howardroark** [comment]
If you run `ssh-add -l` you can see all of the keys are available to your shell session.  The idea is that the the public key partner to one of those is in the `authorized_keys` files of the `stage` user on the `web` vm.  

To make that work you have to add the public key data to the `web:deploy_keys` property of the `project.conf` file:

```
web:
  deploy_keys:
    make_up_some_name: public_key_data_from_file
```

Then provision the web vm after.

**Comment by bgrrtt** [comment]
So after some investigation and your help (adding `web:deploy_keys`), [#4707](https://github.com/mitchellh/vagrant/pull/4707) of [Vagrant](https://github.com/mitchellh/vagrant) helped too. Apparently, after 1.7 (which I am using) if Vagrant thinks? the key is insecure it inserts one itself and ignores/removes the insecure one. This stopped ForwardAgent from working. 

Adding `config.ssh.insert_key = false` to the Vagrantfile solved the issue and sounds like the recommended solution to the common 1.7 problem. I'm still uncertain why Vagrant thinks my ssh key is insecure though, does forwarding mark it automatically as insecure?

**Comment by howardroark** [comment]
Maybe try the `config.ssh.forward_agent` property here... https://docs.vagrantup.com/v2/vagrantfile/ssh_settings.html

I am working on a new feature `fab setup:dev` that will run as the first method of `fab setup`.  The idea will be to setup an initial dev key pair that will be added to the `web` vm.

**Comment by bgrrtt** [comment]
The ops update really helped things. I still think I had to manually update the dev key with my ssh pub key because vagrant doesn't want to import mine and inserts a new "secure" one instead. I possibly don't have forward agent working properly, but that should be in your code anyway, right? 

Anyway, super grateful! Thanks!

**Comment by howardroark** [comment]
Glad you like the `ops` stuff :)  I thought it would be nice to keep it all together... and most people won't really be too concerned to interact with the fabric file anyway.

Yeah... keys are tricky.  It's hard to pin down an approach.  The idea is that `ops setup` creates you a key pair on the VM and ensures that the public key is added to the web vm.  

If you wanted to use your own custom ssh-key you would need to add it to `project.conf` manually...

```
web:
  deploy_keys:
    bgrrtt:  PUBLIC_KEY_DATA
```

Then you would need to ensure that your key forwards properly to the vagrant machine when you ssh in.  From there you should be able to run `ops deploy`. 

PS.  Don't pay attention to `deploy.pem`... that is only to allow read access to the bitbucket repo for the web VM. The deploy really just asks the web vm user to update from the git remote.
